export const experienceData = [
  {
    companyLogo: `UpWork`,
    position: `Sr. Frontend Developer`,
    exDetails: [
      `Lorem ipsum dolor sit amet, consectetur adipiscing elit.`,
      `Ut pretium arcu et massa semper, id fringilla leo semper.`,
      `Sed quis justo ac magna.`,
      `Lorem ipsum dolor sit amet, consectetur adipiscing elit.`,
    ],
    experiencePeriod: `Nov 2021 - Present`,
  },
  {
    companyLogo: `UpWork`,
    position: `Team Lead`,
    exDetails: [
      `Lorem ipsum dolor sit amet, consectetur adipiscing elit.`,
      `Ut pretium arcu et massa semper, id fringilla leo semper.`,
      `Sed quis justo ac magna.`,
      `Lorem ipsum dolor sit amet, consectetur adipiscing elit.`,
      `Lorem ipsum dolor sit amet, consectetur adipiscing elit.`,
    ],
    experiencePeriod: `Jul 2017 - Oct 2021`,
  },
  {
    companyLogo: `UpWork`,
    position: `Full Stack Developer`,
    exDetails: [
      `Lorem ipsum dolor sit amet, consectetur adipiscing elit.`,
      `Ut pretium arcu et massa semper, id fringilla leo semper.`,
      `Sed quis justo ac magna.`,
      `Lorem ipsum dolor sit amet, consectetur adipiscing elit.`,
    ],
    experiencePeriod: `Dec 2015 - May 2017`,
  },
];

export const wordData = [
  {
    image: `https://bnc-content.s3.ap-southeast-1.amazonaws.com/mkt_assets/HomePage_Thumbnail.jpg`,
    companyName: `BNC`,
    detail: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec urna ac tellus volutpat viverra. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae.`,
    techs: [
      `React`,
      `Next.js`,
      `Typescript`,
      `PostgreSQL`,
      `Tailwindcss`,
      `Figma`,
      `Git`,
      `Cypress`,
    ],
  },
  {
    image: `https://www.proprofsproject.com/blog/wp-content/uploads/2022/08/Proprofs-project.jpg`,
    companyName: `ProProfs`,
    detail: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec urna ac tellus volutpat viverra. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae.`,
    techs: [
      `React`,
      `Next.js`,
      `Typescript`,
      `PostgreSQL`,
      `Tailwindcss`,
      `Figma`,
      `Git`,
      `Cypress`,
      `Java`,
      `Javascript`,
    ],
  },
  {
    image: `https://cdn-eahjn.nitrocdn.com/ChEvwayTHZmZJUAdsUNMLXuXZdBprFoQ/assets/images/optimized/rev-6e43cb6/www.spinxdigital.com/app/uploads/2020/02/web_app_development_banner.png`,
    companyName: `SPINX`,
    detail: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec urna ac tellus volutpat viverra. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae.`,
    techs: [
      `React`,
      `Next.js`,
      `Typescript`,
      `PostgreSQL`,
      `Tailwindcss`,
      `Figma`,
      `Git`,
      `Cypress`,
      `Python`,
      `C##`,
    ],
  },
  {
    image: `https://designsystem.digital.gov/img/webp/home/showcase/nih.webp`,
    companyName: `NIH LIBRARY`,
    detail: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec urna ac tellus volutpat viverra. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae.`,
    techs: [
      `React`,
      `Next.js`,
      `Typescript`,
      `PostgreSQL`,
      `Tailwindcss`,
      `Figma`,
      `Git`,
      `Cypress`,
      `Python`,
      `C##`,
      `Javascript`,
      `C++`,
    ],
  },
];
